# Generated by Django 4.2.7 on 2025-10-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cuisine",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=500)),
                ("rating", models.FloatField(blank=True, db_index=True, null=True)),
                ("prep_time", models.IntegerField(blank=True, null=True)),
                ("cook_time", models.IntegerField(blank=True, null=True)),
                (
                    "total_time",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("serves", models.CharField(blank=True, max_length=100, null=True)),
                ("nutrients", models.JSONField(blank=True, null=True)),
                ("continent", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "country_state",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("url", models.URLField(blank=True, max_length=1000, null=True)),
                ("ingredients", models.JSONField(blank=True, null=True)),
                ("instructions", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-rating", "title"],
                "indexes": [
                    models.Index(
                        fields=["-rating"], name="recipes_rec_rating_8e9522_idx"
                    ),
                    models.Index(
                        fields=["cuisine"], name="recipes_rec_cuisine_0fee58_idx"
                    ),
                    models.Index(
                        fields=["total_time"], name="recipes_rec_total_t_156beb_idx"
                    ),
                ],
            },
        ),
    ]
